# -*- coding: utf-8 -*-
"""Python-file-IO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RPR9Le74AN3dc1zWSLV_s1C2dSmmzdsR

### **Python File I/O**
File operations usually takes place in the given order:

1. Open a file
2. Read or write (perform operation)
3. Close the file
"""

# Opening files in Python with built-in function open()
file = open("file.txt")    # open file in present working directory
#file = open("path/to/file.txt")  # specifying the full path of the file to open

"""We can specify the mode while opening a file. In mode, we specify whether we want to read ***r***, write ***w*** or append ***a*** to the file. We can also specify if we want to open the file in text mode or binary mode.

Mode	Description
* **r**	- Opens a file for reading. (default)
* **w**	- Opens a file for writing. Creates a new file if it does not exist or truncates the file if it exists.
* **x**	- Opens a file for exclusive creation. If the file already exists, the operation fails.
* **a**	- Opens a file for appending at the end of the file without truncating it. Creates a new file if it does not exist.
* **t**	- Opens in text mode. (default)
* **b**	- Opens in binary mode.
* **+**	- Opens a file for updating (reading and writing)
"""

file = open("file.txt")      # equivalent to 'r' or 'rt' modes
file = open("file.txt",'w')  # open in text mode
file = open("image.bmp",'r+b') # read and write in binary mode

# Closing files in Python
file = open("file.txt")
# file closing operation
file.close()

# Writing to files in Python
with open("text.txt",'w',encoding = 'utf-8') as f:
   f.write("First file of\n")
   f.write("this file is made up of\n\n")
   f.write("four\n")
   f.write("lines...\n")

# Reading from files in Python
file = open("text.txt",'r')
file.read(5)

print(file.read())  # read the entire file

file = open("text.txt",'r')
file.readline() # Reading first line

file = open("text.txt",'r')
file.readlines() # Reading all lines at a time
